version: '3.8'

services:
  postgres_db:
    image: postgres:15-alpine
    container_name: my_project_db
    environment:
      # Docker Compose автоматически подставит значения из файла .env
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432" # Левый порт — на твоем компе, правый — внутри контейнера
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  redis:
    image: redis:8.10.0-alpine
    container_name: redis_fund
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

volumes:
  pgdata:
  redis_data: