// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: Campaign.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const createCampaign = `-- name: CreateCampaign :one
INSERT INTO campaigns (
    creator_id,
    title,
    description, 
    target_amount,
    end_date 
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, creator_id, title, description, target_amount, current_amount, status, end_date, created_at
`

type CreateCampaignParams struct {
	CreatorID    int32
	Title        string
	Description  pgtype.Text
	TargetAmount decimal.Decimal
	EndDate      pgtype.Timestamptz
}

func (q *Queries) CreateCampaign(ctx context.Context, arg CreateCampaignParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, createCampaign,
		arg.CreatorID,
		arg.Title,
		arg.Description,
		arg.TargetAmount,
		arg.EndDate,
	)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.Title,
		&i.Description,
		&i.TargetAmount,
		&i.CurrentAmount,
		&i.Status,
		&i.EndDate,
		&i.CreatedAt,
	)
	return i, err
}

const decreaseCampaignAmount = `-- name: DecreaseCampaignAmount :one
UPDATE campaigns 
SET current_amount = current_amount - $2
WHERE id = $1 AND current_amount >= $2
RETURNING id, creator_id, title, description, target_amount, current_amount, status, end_date, created_at
`

type DecreaseCampaignAmountParams struct {
	ID            int32
	CurrentAmount decimal.Decimal
}

func (q *Queries) DecreaseCampaignAmount(ctx context.Context, arg DecreaseCampaignAmountParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, decreaseCampaignAmount, arg.ID, arg.CurrentAmount)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.Title,
		&i.Description,
		&i.TargetAmount,
		&i.CurrentAmount,
		&i.Status,
		&i.EndDate,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCampaign = `-- name: DeleteCampaign :exec
DELETE FROM campaigns 
WHERE id = $1
`

func (q *Queries) DeleteCampaign(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteCampaign, id)
	return err
}

const getCampaignByID = `-- name: GetCampaignByID :one
SELECT id, creator_id, title, description, target_amount, current_amount, status, end_date, created_at
FROM campaigns
WHERE id = $1
`

func (q *Queries) GetCampaignByID(ctx context.Context, id int32) (Campaign, error) {
	row := q.db.QueryRow(ctx, getCampaignByID, id)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.Title,
		&i.Description,
		&i.TargetAmount,
		&i.CurrentAmount,
		&i.Status,
		&i.EndDate,
		&i.CreatedAt,
	)
	return i, err
}

const getCampaignByTitle = `-- name: GetCampaignByTitle :one
SELECT id, creator_id, title, description, target_amount, current_amount, status, end_date, created_at
FROM campaigns
WHERE title = $1
`

func (q *Queries) GetCampaignByTitle(ctx context.Context, title string) (Campaign, error) {
	row := q.db.QueryRow(ctx, getCampaignByTitle, title)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.Title,
		&i.Description,
		&i.TargetAmount,
		&i.CurrentAmount,
		&i.Status,
		&i.EndDate,
		&i.CreatedAt,
	)
	return i, err
}

const getCurrentAmount = `-- name: GetCurrentAmount :one
SELECT current_amount 
FROM campaigns
WHERE id = $1
`

func (q *Queries) GetCurrentAmount(ctx context.Context, id int32) (decimal.Decimal, error) {
	row := q.db.QueryRow(ctx, getCurrentAmount, id)
	var current_amount decimal.Decimal
	err := row.Scan(&current_amount)
	return current_amount, err
}

const increaseCampaignAmount = `-- name: IncreaseCampaignAmount :one
UPDATE campaigns 
SET current_amount = current_amount + $2
WHERE id = $1
RETURNING id, creator_id, title, description, target_amount, current_amount, status, end_date, created_at
`

type IncreaseCampaignAmountParams struct {
	ID            int32
	CurrentAmount decimal.Decimal
}

func (q *Queries) IncreaseCampaignAmount(ctx context.Context, arg IncreaseCampaignAmountParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, increaseCampaignAmount, arg.ID, arg.CurrentAmount)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.Title,
		&i.Description,
		&i.TargetAmount,
		&i.CurrentAmount,
		&i.Status,
		&i.EndDate,
		&i.CreatedAt,
	)
	return i, err
}

const listCampaigns = `-- name: ListCampaigns :many
SELECT id, creator_id, title, description, target_amount, current_amount, status, end_date, created_at
FROM campaigns
WHERE status = 'active'
ORDER BY created_at DESC
LIMIT $1
OFFSET $2
`

type ListCampaignsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListCampaigns(ctx context.Context, arg ListCampaignsParams) ([]Campaign, error) {
	rows, err := q.db.Query(ctx, listCampaigns, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Campaign
	for rows.Next() {
		var i Campaign
		if err := rows.Scan(
			&i.ID,
			&i.CreatorID,
			&i.Title,
			&i.Description,
			&i.TargetAmount,
			&i.CurrentAmount,
			&i.Status,
			&i.EndDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
