// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: donate.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDonation = `-- name: CreateDonation :one
INSERT INTO donations (
    user_id,
    campaign_id,
    amount
) VALUES (
    $1, $2, $3
)
RETURNING id, user_id, campaign_id, amount, created_at
`

type CreateDonationParams struct {
	UserID     pgtype.Int4
	CampaignID int32
	Amount     pgtype.Numeric
}

func (q *Queries) CreateDonation(ctx context.Context, arg CreateDonationParams) (Donation, error) {
	row := q.db.QueryRow(ctx, createDonation, arg.UserID, arg.CampaignID, arg.Amount)
	var i Donation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CampaignID,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}

const getListDonations = `-- name: GetListDonations :many
SELECT id, user_id, campaign_id, amount, created_at 
FROM donations
WHERE campaign_id = $1
`

func (q *Queries) GetListDonations(ctx context.Context, campaignID int32) ([]Donation, error) {
	rows, err := q.db.Query(ctx, getListDonations, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Donation
	for rows.Next() {
		var i Donation
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CampaignID,
			&i.Amount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
