// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

type CampaignStatus string

const (
	CampaignStatusActive     CampaignStatus = "active"
	CampaignStatusSuccessful CampaignStatus = "successful"
	CampaignStatusFailed     CampaignStatus = "failed"
	CampaignStatusArchived   CampaignStatus = "archived"
)

func (e *CampaignStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CampaignStatus(s)
	case string:
		*e = CampaignStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CampaignStatus: %T", src)
	}
	return nil
}

type NullCampaignStatus struct {
	CampaignStatus CampaignStatus
	Valid          bool // Valid is true if CampaignStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCampaignStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CampaignStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CampaignStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCampaignStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CampaignStatus), nil
}

type TransactionType string

const (
	TransactionTypeDeposit    TransactionType = "deposit"
	TransactionTypeDonation   TransactionType = "donation"
	TransactionTypeRefund     TransactionType = "refund"
	TransactionTypeWithdrawal TransactionType = "withdrawal"
)

func (e *TransactionType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransactionType(s)
	case string:
		*e = TransactionType(s)
	default:
		return fmt.Errorf("unsupported scan type for TransactionType: %T", src)
	}
	return nil
}

type NullTransactionType struct {
	TransactionType TransactionType
	Valid           bool // Valid is true if TransactionType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTransactionType) Scan(value interface{}) error {
	if value == nil {
		ns.TransactionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TransactionType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTransactionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TransactionType), nil
}

type Campaign struct {
	ID            int32
	CreatorID     int32
	Title         string
	Description   pgtype.Text
	TargetAmount  decimal.Decimal
	CurrentAmount decimal.Decimal
	Status        CampaignStatus
	EndDate       pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
}

type Donation struct {
	ID         int32
	UserID     pgtype.Int4
	CampaignID int32
	Amount     decimal.Decimal
	CreatedAt  pgtype.Timestamptz
}

type Transaction struct {
	ID              int32
	UserID          pgtype.Int4
	DonationID      pgtype.Int4
	TransactionType TransactionType
	Amount          decimal.Decimal
	CreatedAt       pgtype.Timestamptz
}

type User struct {
	ID           int32
	Email        string
	PasswordHash string
	FirstName    pgtype.Text
	LastName     pgtype.Text
	Balance      decimal.Decimal
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
}
