// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateCampaign(ctx context.Context, arg CreateCampaignParams) (Campaign, error)
	CreateDonation(ctx context.Context, arg CreateDonationParams) (Donation, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DecreaseCampaignAmount(ctx context.Context, arg DecreaseCampaignAmountParams) (Campaign, error)
	DeleteCampaign(ctx context.Context, id int32) error
	DeleteUser(ctx context.Context, id int32) error
	GetByEmail(ctx context.Context, email string) (User, error)
	GetByID(ctx context.Context, id int32) (User, error)
	GetCampaignByID(ctx context.Context, id int32) (Campaign, error)
	GetCurrentAmount(ctx context.Context, id int32) (pgtype.Numeric, error)
	GetListDonations(ctx context.Context, campaignID int32) ([]Donation, error)
	IncreaseCampaignAmount(ctx context.Context, arg IncreaseCampaignAmountParams) (Campaign, error)
	TopUp(ctx context.Context, arg TopUpParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	Withdraw(ctx context.Context, arg WithdrawParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
