// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transation.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const addTX = `-- name: AddTX :one
INSERT INTO transactions
(user_id, 
donation_id, 
transaction_type, 
amount, reated_at)
VALUES (
    $1, $2, $3, $4, NOW()
)
RETURNING id, user_id, donation_id, transaction_type, amount, created_at
`

type AddTXParams struct {
	UserID          pgtype.Int4
	DonationID      pgtype.Int4
	TransactionType TransactionType
	Amount          decimal.Decimal
}

func (q *Queries) AddTX(ctx context.Context, arg AddTXParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, addTX,
		arg.UserID,
		arg.DonationID,
		arg.TransactionType,
		arg.Amount,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DonationID,
		&i.TransactionType,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}

const historyTX = `-- name: HistoryTX :many
SELECT id, user_id, donation_id, transaction_type, amount, created_at 
FROM transactions
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) HistoryTX(ctx context.Context, userID pgtype.Int4) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, historyTX, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DonationID,
			&i.TransactionType,
			&i.Amount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
