// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const addBalance = `-- name: AddBalance :exec
UPDATE users 
SET balance = balance + $2
WHERE id = $1
`

type AddBalanceParams struct {
	ID      int32
	Balance decimal.Decimal
}

func (q *Queries) AddBalance(ctx context.Context, arg AddBalanceParams) error {
	_, err := q.db.Exec(ctx, addBalance, arg.ID, arg.Balance)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    email, password_hash, 
    first_name, 
    last_name
) VALUES (
    $1, $2, $3, $4
)
RETURNING  id, email, password_hash, first_name, last_name, balance, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	Email        string
	PasswordHash string
	FirstName    pgtype.Text
	LastName     pgtype.Text
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.FirstName,
		arg.LastName,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users 
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getBalance = `-- name: GetBalance :one
SELECT balance
FROM users
WHERE id = $1
AND deleted_at IS NULL
`

func (q *Queries) GetBalance(ctx context.Context, id int32) (decimal.Decimal, error) {
	row := q.db.QueryRow(ctx, getBalance, id)
	var balance decimal.Decimal
	err := row.Scan(&balance)
	return balance, err
}

const getByEmail = `-- name: GetByEmail :one
SELECT id, email, password_hash, first_name, last_name, balance, created_at, updated_at, deleted_at
FROM users
WHERE email = $1
AND deleted_at IS NULL
`

func (q *Queries) GetByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getByID = `-- name: GetByID :one
SELECT id, email, password_hash, first_name, last_name, balance, created_at, updated_at, deleted_at
FROM users
WHERE id = $1
AND deleted_at IS NULL
`

func (q *Queries) GetByID(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, getByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const restoreUser = `-- name: RestoreUser :one
UPDATE users 
SET deleted_at = NULL 
WHERE id = $1 AND deleted_at IS NOT NULL
RETURNING id, email, password_hash, first_name, last_name, balance, created_at, updated_at, deleted_at
`

func (q *Queries) RestoreUser(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, restoreUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
UPDATE users
SET deleted_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteUser(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, softDeleteUser, id)
	return err
}

const subtractBalance = `-- name: SubtractBalance :execrows
UPDATE users 
SET balance = balance - $2
WHERE id = $1
AND balance >= $2
`

type SubtractBalanceParams struct {
	ID      int32
	Balance decimal.Decimal
}

func (q *Queries) SubtractBalance(ctx context.Context, arg SubtractBalanceParams) (int64, error) {
	result, err := q.db.Exec(ctx, subtractBalance, arg.ID, arg.Balance)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users 
SET 
    email = $1,
    password_hash = $2,
    first_name = $3,
    last_name = $4,
    updated_at = NOW()
WHERE id = $5
RETURNING  id, email, password_hash, first_name, last_name, balance, created_at, updated_at, deleted_at
`

type UpdateUserParams struct {
	Email        string
	PasswordHash string
	FirstName    pgtype.Text
	LastName     pgtype.Text
	ID           int32
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.Email,
		arg.PasswordHash,
		arg.FirstName,
		arg.LastName,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const userResponce = `-- name: UserResponce :one
SELECT id, email, first_name, last_name, balance, created_at, updated_at, deleted_at
FROM users
WHERE id = $1
`

type UserResponceRow struct {
	ID        int32
	Email     string
	FirstName pgtype.Text
	LastName  pgtype.Text
	Balance   decimal.Decimal
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

func (q *Queries) UserResponce(ctx context.Context, id int32) (UserResponceRow, error) {
	row := q.db.QueryRow(ctx, userResponce, id)
	var i UserResponceRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
